name: Build and deploy
on: 
  push:
  workflow_dispatch:

env:
 REGISTRY: ghcr.io
 IMAGE_NAME: ${{ github.repository }}
 
jobs:
  build-and-publish:
    name: "Prod: Bygg, test og push Docker image"
    runs-on: ubuntu-latest
    permissions:
      packages: 'write'
      contents: 'read'
      id-token: 'write'
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: navikt/teamsykmelding-github-actions-workflows/actions/yarn-cached@node-20
        with:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: bun run lint
      - run: bun run build
        env:
          NEXT_PUBLIC_ENVIRONMENT: production
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Push docker image to GHCR
        uses: docker/build-push-action@v4
        id: docker-build-push
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
